# Generated by Django 5.2.16 on 2026-07-09 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dialysis", "0002_dialysissessionlog_dialysis_center_and_more"),
        ("patients", "0002_dialysiscenter_clinicalnote_is_voided_and_more"),
        ("vascular_access", "0002_catheterdetail_device_infectiondetail_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_code",
                    models.CharField(
                        help_text="A1–A15 per product spec §10.", max_length=8
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("red", "Same-day action"),
                            ("amber", "This week"),
                            ("yellow", "Housekeeping"),
                        ],
                        max_length=8,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("snoozed", "Snoozed"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "first_raised_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("snoozed_until", models.DateField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.CharField(blank=True, max_length=500)),
                ("dedupe_key", models.CharField(max_length=120)),
                (
                    "access",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="vascular_access.vascularaccess",
                    ),
                ),
                (
                    "complication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="vascular_access.accesscomplication",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="patients.patient",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="dialysis.dialysissessionlog",
                    ),
                ),
            ],
            options={
                "ordering": ["severity", "-first_raised_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity"], name="alert_status_severity_idx"
                    ),
                    models.Index(fields=["patient"], name="alert_patient_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "resolved"), _negated=True),
                            models.Q(("resolution_note", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="alert_resolution_requires_note",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "snoozed"), _negated=True),
                            ("snoozed_until__isnull", False),
                            _connector="OR",
                        ),
                        name="alert_snooze_requires_date",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["active", "snoozed"])),
                        fields=("dedupe_key",),
                        name="unique_live_alert_dedupe_key",
                    ),
                ],
            },
        ),
    ]
