# Generated by Django 5.2.16 on 2026-07-09 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("patients", "0002_dialysiscenter_clinicalnote_is_voided_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dialysis_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="patients.dialysiscenter",
            ),
        ),
    ]
