# Generated by Django 5.2.16 on 2026-07-09 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_date", models.DateField()),
                (
                    "planned_access_type",
                    models.CharField(
                        choices=[
                            ("radiocephalic_avf", "Radiocephalic AVF"),
                            ("brachiocephalic_avf", "Brachiocephalic AVF"),
                            ("brachiobasilic_avf", "Brachiobasilic AVF"),
                            ("transposed_basilic_avf", "Transposed basilic AVF"),
                            ("prosthetic_avg", "Prosthetic AVG"),
                            (
                                "tunneled_cuffed_catheter",
                                "Tunneled cuffed dialysis catheter",
                            ),
                            ("temporary_catheter", "Temporary dialysis catheter"),
                            ("hero_graft", "HeRO graft"),
                            ("complex_access", "Complex access"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "planned_side",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("n_a", "Not applicable"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("performed", "Performed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_plans",
                        to="patients.patient",
                    ),
                ),
                (
                    "planned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-plan_date"],
            },
        ),
        migrations.CreateModel(
            name="VascularAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("radiocephalic_avf", "Radiocephalic AVF"),
                            ("brachiocephalic_avf", "Brachiocephalic AVF"),
                            ("brachiobasilic_avf", "Brachiobasilic AVF"),
                            ("transposed_basilic_avf", "Transposed basilic AVF"),
                            ("prosthetic_avg", "Prosthetic AVG"),
                            (
                                "tunneled_cuffed_catheter",
                                "Tunneled cuffed dialysis catheter",
                            ),
                            ("temporary_catheter", "Temporary dialysis catheter"),
                            ("hero_graft", "HeRO graft"),
                            ("complex_access", "Complex access"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "laterality",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("n_a", "Not applicable"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        choices=[
                            ("forearm", "Forearm"),
                            ("upper_arm", "Upper arm"),
                            ("thigh", "Thigh"),
                            ("chest_wall", "Chest wall"),
                            ("internal_jugular", "Internal jugular vein"),
                            ("subclavian", "Subclavian vein"),
                            ("femoral", "Femoral vein"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "graft_material",
                    models.CharField(
                        blank=True,
                        help_text="For AVG/HeRO: prosthetic material and caliber.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("maturing", "Created, maturing"),
                            ("ready", "Mature, awaiting first cannulation"),
                            ("in_use", "In use for dialysis"),
                            ("failed_maturation", "Never matured (nonmaturation)"),
                            ("abandoned", "Abandoned"),
                            ("removed", "Removed"),
                        ],
                        default="maturing",
                        max_length=32,
                    ),
                ),
                (
                    "created_on",
                    models.DateField(
                        help_text="Date of the creation/insertion procedure."
                    ),
                ),
                (
                    "maturation_confirmed_on",
                    models.DateField(
                        blank=True,
                        help_text="Date maturity was confirmed clinically or on ultrasound.",
                        null=True,
                    ),
                ),
                ("first_cannulation_on", models.DateField(blank=True, null=True)),
                (
                    "first_successful_cannulation_on",
                    models.DateField(
                        blank=True,
                        help_text="First cannulation that delivered an adequate dialysis session.",
                        null=True,
                    ),
                ),
                ("dialysis_use_confirmed_on", models.DateField(blank=True, null=True)),
                ("abandoned_on", models.DateField(blank=True, null=True)),
                (
                    "abandonment_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nonmaturation", "Nonmaturation"),
                            ("thrombosis", "Thrombosis"),
                            ("infection", "Infection"),
                            ("steal_syndrome", "Steal syndrome / ischemia"),
                            ("aneurysm", "Aneurysm / pseudoaneurysm"),
                            ("central_vein_stenosis", "Central vein stenosis"),
                            ("catheter_dysfunction", "Catheter dysfunction"),
                            (
                                "no_longer_needed",
                                "No longer needed (working access / transplant)",
                            ),
                            ("patient_death", "Patient death"),
                            ("patient_choice", "Patient choice"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "removed_on",
                    models.DateField(
                        blank=True,
                        help_text="Removal/ligation date (mainly catheters).",
                        null=True,
                    ),
                ),
                (
                    "removal_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nonmaturation", "Nonmaturation"),
                            ("thrombosis", "Thrombosis"),
                            ("infection", "Infection"),
                            ("steal_syndrome", "Steal syndrome / ischemia"),
                            ("aneurysm", "Aneurysm / pseudoaneurysm"),
                            ("central_vein_stenosis", "Central vein stenosis"),
                            ("catheter_dysfunction", "Catheter dysfunction"),
                            (
                                "no_longer_needed",
                                "No longer needed (working access / transplant)",
                            ),
                            ("patient_death", "Patient death"),
                            ("patient_choice", "Patient choice"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "dialysis_use_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nephrologist confirming the access is functioning for dialysis.",
                        limit_choices_to={"role": "nephrologist"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="patients.patient",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accesses",
                        to="vascular_access.accessplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "vascular access",
                "verbose_name_plural": "vascular accesses",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="AccessComplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complication_type",
                    models.CharField(
                        choices=[
                            ("nonmaturation", "Nonmaturation"),
                            ("thrombosis", "Thrombosis"),
                            ("stenosis", "Stenosis"),
                            (
                                "access_site_infection",
                                "Access site infection (fistula/graft)",
                            ),
                            ("crbsi", "Catheter-related bloodstream infection"),
                            ("exit_site_infection", "Exit-site infection"),
                            ("tunnel_infection", "Tunnel infection"),
                            ("catheter_dysfunction", "Catheter dysfunction"),
                            (
                                "steal_syndrome",
                                "Steal syndrome / access-related ischemia",
                            ),
                            ("aneurysm", "Aneurysm"),
                            ("pseudoaneurysm", "Pseudoaneurysm"),
                            ("bleeding", "Bleeding"),
                            ("hematoma_seroma", "Hematoma / seroma"),
                            ("central_vein_stenosis", "Central vein stenosis"),
                            (
                                "high_output_heart_failure",
                                "High-flow / high-output heart failure",
                            ),
                            ("neuropathy", "Access-related neuropathy"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("onset_date", models.DateField()),
                (
                    "management",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conservative", "Conservative / observation"),
                            (
                                "medical",
                                "Medical therapy (antibiotics, anticoagulation…)",
                            ),
                            ("endovascular", "Endovascular intervention"),
                            ("surgical", "Surgical intervention"),
                            (
                                "catheter_exchange_removal",
                                "Catheter exchange or removal",
                            ),
                            ("access_abandoned", "Access abandoned"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "organism",
                    models.CharField(
                        blank=True,
                        help_text="Culture result for infectious complications.",
                        max_length=255,
                    ),
                ),
                ("resolved", models.BooleanField(blank=True, null=True)),
                ("resolution_date", models.DateField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_complications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complications",
                        to="vascular_access.vascularaccess",
                    ),
                ),
            ],
            options={
                "ordering": ["-onset_date"],
            },
        ),
        migrations.CreateModel(
            name="VesselMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exam_date", models.DateField()),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("n_a", "Not applicable"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "cephalic_vein_diameter_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "basilic_vein_diameter_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "radial_artery_diameter_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "brachial_artery_diameter_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("arterial_calcification", models.BooleanField(default=False)),
                (
                    "central_vein_patency_concern",
                    models.BooleanField(
                        default=False,
                        help_text="Suspected or documented central venous stenosis/occlusion.",
                    ),
                ),
                ("findings", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vessel_mappings",
                        to="patients.patient",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vessel_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vessel mapping",
                "ordering": ["-exam_date"],
            },
        ),
        migrations.AddField(
            model_name="accessplan",
            name="based_on_mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans",
                to="vascular_access.vesselmapping",
            ),
        ),
        migrations.CreateModel(
            name="AccessProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "procedure_type",
                    models.CharField(
                        choices=[
                            ("creation", "Access creation / catheter insertion"),
                            (
                                "second_stage_transposition",
                                "Second-stage transposition / superficialization",
                            ),
                            ("angioplasty", "Percutaneous angioplasty"),
                            ("stent", "Stent placement"),
                            ("surgical_revision", "Open surgical revision"),
                            ("thrombectomy_surgical", "Surgical thrombectomy"),
                            (
                                "thrombectomy_endovascular",
                                "Endovascular thrombectomy / thrombolysis",
                            ),
                            ("aneurysm_repair", "Aneurysm / pseudoaneurysm repair"),
                            ("banding_flow_reduction", "Banding / flow reduction"),
                            (
                                "dril_or_ischemia_procedure",
                                "DRIL / ischemia-correcting procedure",
                            ),
                            ("ligation", "Ligation"),
                            ("catheter_exchange", "Catheter exchange over wire"),
                            ("catheter_reposition", "Catheter repositioning"),
                            ("catheter_removal", "Catheter removal"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("performed_on", models.DateField()),
                (
                    "urgency",
                    models.CharField(
                        choices=[("elective", "Elective"), ("urgent", "Urgent")],
                        default="elective",
                        max_length=16,
                    ),
                ),
                (
                    "anesthesia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("local", "Local"),
                            ("regional_block", "Regional block"),
                            ("sedation", "Sedation"),
                            ("general", "General"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "technical_success",
                    models.BooleanField(
                        blank=True,
                        help_text="Immediate technical success; empty until assessed.",
                        null=True,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "indication_complication",
                    models.ForeignKey(
                        blank=True,
                        help_text="Complication this procedure treats, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_procedures",
                        to="vascular_access.accesscomplication",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_procedures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="vascular_access.vascularaccess",
                    ),
                ),
            ],
            options={
                "ordering": ["performed_on", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("procedure_type", "creation")),
                        fields=("access",),
                        name="one_creation_procedure_per_access",
                    )
                ],
            },
        ),
    ]
