# Generated by Django 5.2.16 on 2026-07-09 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_dialysiscenter_clinicalnote_is_voided_and_more"),
        ("vascular_access", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatheterDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lumen_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "catheter_length_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "tip_position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("right_atrium", "Right atrium"),
                            ("cavoatrial_junction", "Cavoatrial junction"),
                            ("svc", "Superior vena cava"),
                            ("other", "Other"),
                            ("not_recorded", "Not recorded"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "insertion_technique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("us_and_fluoro", "Ultrasound + fluoroscopy"),
                            ("us_only", "Ultrasound only"),
                            ("landmark", "Landmark technique"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "reason_for_catheter",
                    models.CharField(
                        choices=[
                            ("urgent_start", "Urgent dialysis start"),
                            ("bridge_avf_maturing", "Bridge while AVF/AVG matures"),
                            ("options_exhausted", "Permanent access options exhausted"),
                            ("patient_refusal_of_avf", "Patient refusal of AVF/AVG"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("exit_site_note", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("graft", "Prosthetic graft"),
                            ("tunneled_catheter", "Tunneled cuffed catheter"),
                            ("temporary_catheter", "Temporary catheter"),
                            ("stent", "Stent"),
                            ("stent_graft", "Stent graft"),
                            ("balloon", "Angioplasty balloon"),
                            ("hero_component", "HeRO component"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("manufacturer", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "size_spec",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "6 mm × 40 cm", "23 cm, 14.5 F"',
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["manufacturer", "model_name", "size_spec"],
            },
        ),
        migrations.CreateModel(
            name="InfectionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("blood_cultures_taken", models.BooleanField(blank=True, null=True)),
                (
                    "organism",
                    models.CharField(
                        blank=True,
                        help_text="Culture result (free text; coded list later).",
                        max_length=255,
                    ),
                ),
                ("antibiotic_therapy", models.CharField(blank=True, max_length=255)),
                (
                    "hospitalization_required",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "access_removed_or_exchanged",
                    models.BooleanField(
                        blank=True,
                        help_text="Catheter pulled / graft excised because of this infection.",
                        null=True,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resolved", "Resolved"),
                            ("recurrent", "Recurrent"),
                            ("metastatic_infection", "Metastatic infection"),
                            ("death_related", "Contributed to death"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "verbose_name": "infection detail",
            },
        ),
        migrations.CreateModel(
            name="MaturationAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_voided", models.BooleanField(default=False)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                ("assessment_date", models.DateField()),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("postop_check", "Post-operative check (~2 weeks)"),
                            ("clinical", "Clinical assessment"),
                            ("duplex", "Duplex ultrasound"),
                            ("pre_cannulation", "Pre-cannulation check"),
                        ],
                        max_length=24,
                    ),
                ),
                ("thrill_present", models.BooleanField(blank=True, null=True)),
                ("bruit_present", models.BooleanField(blank=True, null=True)),
                (
                    "outflow_vein_diameter_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "flow_volume_ml_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "vein_depth_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("on_track", "Maturing as expected"),
                            ("mature", "Mature — ready for cannulation"),
                            ("delayed", "Delayed — intervention to consider"),
                            ("failed", "Failed maturation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["assessment_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lot_number", models.CharField(blank=True, max_length=64)),
                ("serial_number", models.CharField(blank=True, max_length=64)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ThrombosisDysfunctionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "suspected_cause",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "juxta_anastomotic_stenosis",
                                "Juxta-anastomotic stenosis",
                            ),
                            ("outflow_stenosis", "Outflow stenosis"),
                            ("central_stenosis", "Central vein stenosis"),
                            ("intra_access_stenosis", "Intra-access stenosis"),
                            ("hypotension", "Hypotension"),
                            ("hypercoagulability", "Hypercoagulability"),
                            ("external_compression", "External compression"),
                            ("fibrin_sheath", "Fibrin sheath (catheter)"),
                            ("malposition", "Malposition (catheter)"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("stenosis_location", models.CharField(blank=True, max_length=100)),
                ("thrombolytic_lock_used", models.BooleanField(blank=True, null=True)),
                ("flow_restored", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "thrombosis/dysfunction detail",
            },
        ),
        migrations.RemoveConstraint(
            model_name="accessprocedure",
            name="one_creation_procedure_per_access",
        ),
        migrations.RemoveField(
            model_name="accesscomplication",
            name="organism",
        ),
        migrations.AddField(
            model_name="accesscomplication",
            name="is_voided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accesscomplication",
            name="triage_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending physician triage"),
                    ("triaged", "Triaged"),
                ],
                default="triaged",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="accesscomplication",
            name="void_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="accessplan",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="vascular_access.accessplan",
            ),
        ),
        migrations.AddField(
            model_name="accessprocedure",
            name="is_voided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accessprocedure",
            name="void_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vascularaccess",
            name="is_voided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vascularaccess",
            name="void_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="accesscomplication",
            index=models.Index(
                fields=["access", "onset_date"], name="complication_access_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesscomplication",
            index=models.Index(
                fields=["complication_type"], name="complication_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesscomplication",
            index=models.Index(
                condition=models.Q(("triage_status", "pending")),
                fields=["triage_status"],
                name="complication_pending_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accessplan",
            index=models.Index(fields=["status"], name="plan_status_idx"),
        ),
        migrations.AddIndex(
            model_name="vascularaccess",
            index=models.Index(
                fields=["patient", "-created_on"], name="access_patient_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vascularaccess",
            index=models.Index(fields=["access_type"], name="access_type_idx"),
        ),
        migrations.AddIndex(
            model_name="vascularaccess",
            index=models.Index(
                condition=models.Q(("status__in", ["maturing", "ready", "in_use"])),
                fields=["status"],
                name="access_active_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vesselmapping",
            index=models.Index(
                fields=["patient", "-exam_date"], name="mapping_patient_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="accesscomplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resolution_date__isnull", True),
                    ("resolution_date__gte", models.F("onset_date")),
                    _connector="OR",
                ),
                name="complication_resolution_after_onset",
            ),
        ),
        migrations.AddConstraint(
            model_name="vascularaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maturation_confirmed_on__isnull", True),
                    ("maturation_confirmed_on__gte", models.F("created_on")),
                    _connector="OR",
                ),
                name="access_maturation_after_creation",
            ),
        ),
        migrations.AddConstraint(
            model_name="vascularaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("first_cannulation_on__isnull", True),
                    ("first_cannulation_on__gte", models.F("created_on")),
                    _connector="OR",
                ),
                name="access_cannulation_after_creation",
            ),
        ),
        migrations.AddConstraint(
            model_name="vascularaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("abandoned_on__isnull", True),
                    ("abandoned_on__gte", models.F("created_on")),
                    _connector="OR",
                ),
                name="access_abandonment_after_creation",
            ),
        ),
        migrations.AddConstraint(
            model_name="vascularaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("removed_on__isnull", True),
                    ("removed_on__gte", models.F("created_on")),
                    _connector="OR",
                ),
                name="access_removal_after_creation",
            ),
        ),
        migrations.AddConstraint(
            model_name="vascularaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("abandonment_reason", ""),
                    ("abandoned_on__isnull", False),
                    _connector="OR",
                ),
                name="access_abandon_reason_requires_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="vascularaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("removal_reason", ""),
                    ("removed_on__isnull", False),
                    _connector="OR",
                ),
                name="access_removal_reason_requires_date",
            ),
        ),
        migrations.AddField(
            model_name="catheterdetail",
            name="access",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catheter_detail",
                to="vascular_access.vascularaccess",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("device_type", "manufacturer", "model_name", "size_spec"),
                name="unique_device_catalog_entry",
            ),
        ),
        migrations.AddField(
            model_name="catheterdetail",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="catheter_details",
                to="vascular_access.device",
            ),
        ),
        migrations.AddField(
            model_name="infectiondetail",
            name="complication",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="infection_detail",
                to="vascular_access.accesscomplication",
            ),
        ),
        migrations.AddField(
            model_name="maturationassessment",
            name="access",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maturation_assessments",
                to="vascular_access.vascularaccess",
            ),
        ),
        migrations.AddField(
            model_name="maturationassessment",
            name="assessed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maturation_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proceduredevice",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uses",
                to="vascular_access.device",
            ),
        ),
        migrations.AddField(
            model_name="proceduredevice",
            name="procedure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_uses",
                to="vascular_access.accessprocedure",
            ),
        ),
        migrations.AddField(
            model_name="accessprocedure",
            name="devices",
            field=models.ManyToManyField(
                blank=True,
                help_text="Implanted/used devices with lot traceability.",
                related_name="procedures",
                through="vascular_access.ProcedureDevice",
                to="vascular_access.device",
            ),
        ),
        migrations.AddIndex(
            model_name="accessprocedure",
            index=models.Index(
                fields=["access", "performed_on"], name="procedure_access_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessprocedure",
            index=models.Index(fields=["procedure_type"], name="procedure_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="accessprocedure",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_voided", False), ("procedure_type", "creation")
                ),
                fields=("access",),
                name="one_creation_procedure_per_access",
            ),
        ),
        migrations.AddField(
            model_name="thrombosisdysfunctiondetail",
            name="complication",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thrombosis_detail",
                to="vascular_access.accesscomplication",
            ),
        ),
        migrations.AddConstraint(
            model_name="catheterdetail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lumen_count__isnull", True),
                    models.Q(("lumen_count__gte", 1), ("lumen_count__lte", 3)),
                    _connector="OR",
                ),
                name="catheter_lumen_count_1_to_3",
            ),
        ),
        migrations.AddIndex(
            model_name="maturationassessment",
            index=models.Index(
                fields=["access", "assessment_date"], name="maturation_access_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="proceduredevice",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="device_quantity_positive",
            ),
        ),
    ]
