# Generated by Django 5.2.16 on 2026-07-09 18:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registry_code",
                    models.CharField(
                        editable=False,
                        help_text="Stable pseudonymous identifier used in exports (e.g. DA-000042).",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="Georgian personal number (piradi nomeri), if known.",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$", "Georgian personal number is 11 digits."
                            )
                        ],
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=8
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Region / city of residence.",
                        max_length=100,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "dialysis_center",
                    models.CharField(
                        blank=True,
                        help_text="Dialysis center the patient attends, if on HD.",
                        max_length=255,
                    ),
                ),
                (
                    "referral_date",
                    models.DateField(
                        blank=True,
                        help_text="Date referred to the vascular access service.",
                        null=True,
                    ),
                ),
                (
                    "ckd_stage_at_referral",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stage_4", "CKD stage 4 (predialysis)"),
                            ("stage_5", "CKD stage 5 (predialysis)"),
                            ("stage_5d", "CKD stage 5D (already on dialysis)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "primary_renal_disease",
                    models.CharField(
                        choices=[
                            ("diabetic_nephropathy", "Diabetic nephropathy"),
                            ("hypertensive_nephropathy", "Hypertensive nephropathy"),
                            ("glomerulonephritis", "Glomerulonephritis"),
                            ("polycystic_kidney_disease", "Polycystic kidney disease"),
                            ("obstructive_uropathy", "Obstructive uropathy"),
                            ("interstitial_nephritis", "Interstitial nephritis"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("dialysis_start_date", models.DateField(blank=True, null=True)),
                ("has_diabetes", models.BooleanField(default=False)),
                ("has_hypertension", models.BooleanField(default=False)),
                ("has_coronary_artery_disease", models.BooleanField(default=False)),
                ("has_heart_failure", models.BooleanField(default=False)),
                ("has_peripheral_arterial_disease", models.BooleanField(default=False)),
                (
                    "has_previous_central_venous_catheter",
                    models.BooleanField(
                        default=False,
                        help_text="Any prior central venous catheter (risk of central stenosis).",
                    ),
                ),
                (
                    "on_anticoagulation_or_antiplatelet",
                    models.BooleanField(default=False),
                ),
                ("comorbidity_notes", models.TextField(blank=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("predialysis", "CKD 4–5, predialysis"),
                            ("on_hemodialysis", "On hemodialysis"),
                            ("transplanted", "Kidney transplant recipient"),
                            ("transferred_out", "Transferred to another center"),
                            ("lost_to_follow_up", "Lost to follow-up"),
                            ("deceased", "Deceased"),
                        ],
                        default="predialysis",
                        max_length=32,
                    ),
                ),
                ("current_status_date", models.DateField(blank=True, null=True)),
                (
                    "responsible_nephrologist",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "nephrologist"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nephrology_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_surgeon",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "vascular_surgeon"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgical_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_notes",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("predialysis", "CKD 4–5, predialysis"),
                            ("on_hemodialysis", "On hemodialysis"),
                            ("transplanted", "Kidney transplant recipient"),
                            ("transferred_out", "Transferred to another center"),
                            ("lost_to_follow_up", "Lost to follow-up"),
                            ("deceased", "Deceased"),
                        ],
                        max_length=32,
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        help_text="Cause of death, destination center, transplant details, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_status_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("national_id", ""), _negated=True),
                fields=("national_id",),
                name="unique_national_id_when_present",
            ),
        ),
    ]
