# Generated by Django 5.2.16 on 2026-07-09 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DialysisCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="clinicalnote",
            name="is_voided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clinicalnote",
            name="void_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this row was a duplicate registration; follow the pointer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_duplicates",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="patientstatusevent",
            name="is_voided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientstatusevent",
            name="void_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="patientstatusevent",
            index=models.Index(
                fields=["patient", "-event_date"], name="statusevent_patient_date_idx"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="dialysis_center",
            field=models.ForeignKey(
                blank=True,
                help_text="Dialysis center the patient attends, if on HD.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="patients.dialysiscenter",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["last_name", "first_name"], name="patient_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["current_status"], name="patient_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("merged_into__isnull", True),
                    models.Q(("merged_into", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="patient_not_merged_into_self",
            ),
        ),
    ]
