# Generated by Django 5.2.16 on 2026-07-09 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vascular_access", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DialysisSessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_date", models.DateField()),
                (
                    "cannulation_successful",
                    models.BooleanField(
                        blank=True,
                        help_text="For fistula/graft sessions; leave empty for catheters.",
                        null=True,
                    ),
                ),
                (
                    "blood_flow_rate_ml_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Achieved pump speed (Qb), mL/min.",
                        null=True,
                    ),
                ),
                (
                    "arterial_pressure_mmhg",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "venous_pressure_mmhg",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "problem",
                    models.CharField(
                        choices=[
                            ("none", "No problem"),
                            ("difficult_cannulation", "Difficult cannulation"),
                            ("failed_cannulation", "Failed cannulation"),
                            ("infiltration_hematoma", "Infiltration / hematoma"),
                            ("low_blood_flow", "Low blood flow"),
                            ("high_venous_pressure", "High venous pressure"),
                            (
                                "high_negative_arterial_pressure",
                                "High negative arterial pressure",
                            ),
                            ("prolonged_bleeding", "Prolonged post-dialysis bleeding"),
                            ("pain", "Pain during session"),
                            ("catheter_flow_problem", "Catheter flow problem"),
                            ("suspected_infection", "Suspected access infection"),
                            ("other", "Other"),
                        ],
                        default="none",
                        max_length=40,
                    ),
                ),
                ("session_completed", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialysis_logs",
                        to="vascular_access.vascularaccess",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dialysis_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dialysis session log",
                "ordering": ["-session_date", "-id"],
            },
        ),
    ]
