# Generated by Django 5.2.16 on 2026-07-09 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialysis", "0001_initial"),
        ("patients", "0002_dialysiscenter_clinicalnote_is_voided_and_more"),
        ("vascular_access", "0002_catheterdetail_device_infectiondetail_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dialysissessionlog",
            name="dialysis_center",
            field=models.ForeignKey(
                blank=True,
                help_text="Where the session happened; defaults to the patient's center.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_logs",
                to="patients.dialysiscenter",
            ),
        ),
        migrations.AddField(
            model_name="dialysissessionlog",
            name="is_voided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dialysissessionlog",
            name="needle_gauge",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dialysissessionlog",
            name="void_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="dialysissessionlog",
            index=models.Index(
                fields=["access", "-session_date"], name="session_access_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dialysissessionlog",
            index=models.Index(
                condition=models.Q(("problem", "none"), _negated=True),
                fields=["problem"],
                name="session_problem_idx",
            ),
        ),
    ]
