# Generated by Django 5.2.16 on 2026-07-09 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0002_dialysiscenter_clinicalnote_is_voided_and_more"),
        ("vascular_access", "0002_catheterdetail_device_infectiondetail_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUpTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("plan_access", "Plan vascular access"),
                            ("mapping_needed", "Vascular mapping needed"),
                            ("schedule_creation", "Schedule creation procedure"),
                            ("postop_check", "Post-operative check (~2 weeks)"),
                            ("maturation_assessment", "Maturation assessment"),
                            (
                                "inform_center_ready",
                                "Inform dialysis center — ready for cannulation",
                            ),
                            (
                                "fistulogram_decision",
                                "Fistulogram / intervention decision",
                            ),
                            (
                                "plan_permanent_access",
                                "Plan permanent access (catheter-only patient)",
                            ),
                            ("remove_catheter", "Remove tunneled catheter"),
                            ("treat_complication", "Treat / triage complication"),
                            ("early_review", "Early review (technical failure)"),
                            ("chase_session_logs", "Chase missing session logs"),
                            ("custom", "Custom task"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("details", models.TextField(blank=True)),
                ("due_date", models.DateField()),
                (
                    "assigned_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vascular_surgeon", "Vascular surgeon"),
                            ("nephrologist", "Nephrologist"),
                            ("dialysis_nurse", "Dialysis nurse"),
                            ("registry_coordinator", "Registry coordinator"),
                            ("researcher", "Admin / research user"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("deferred", "Deferred"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("deferred_until", models.DateField(blank=True, null=True)),
                ("deferral_reason", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("system", "System-generated"),
                            ("manual", "Manually created"),
                        ],
                        default="system",
                        max_length=8,
                    ),
                ),
                ("dedupe_key", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "access",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_tasks",
                        to="vascular_access.vascularaccess",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_up_tasks",
                        to="vascular_access.accesscomplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_tasks",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "due_date"], name="task_status_due_idx"
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="task_assignee_status_idx",
                    ),
                    models.Index(fields=["patient"], name="task_patient_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "deferred"), _negated=True),
                            models.Q(
                                ("deferred_until__isnull", False),
                                models.Q(("deferral_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="task_deferral_requires_date_and_reason",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("dedupe_key__isnull", False), ("status", "open")
                        ),
                        fields=("dedupe_key",),
                        name="unique_open_task_dedupe_key",
                    ),
                ],
            },
        ),
    ]
