# Generated by Django 5.2.16 on 2026-07-09 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.CharField(
                        choices=[
                            ("patients", "Patients (pseudonymized)"),
                            ("accesses", "Access episodes"),
                            ("procedures", "Procedures"),
                            ("complications", "Complications"),
                            ("sessions_aggregate", "Session aggregates"),
                            ("full_bundle", "Full anonymized bundle"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, help_text="Cohort parameters used."
                    ),
                ),
                ("row_count", models.PositiveIntegerField()),
                ("file_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-exported_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "-exported_at"],
                        name="export_user_date_idx",
                    )
                ],
            },
        ),
    ]
